### ISSUE TITLE
Some dependent required? fatal error: cub/cub.cuh: No such file or directory

### ISSUE THREAD

**Issue by dancingpipi** [sleeepyjack/warpcore#1]
<img width="773" alt="image" src="https://user-images.githubusercontent.com/20511825/117790395-e35a4e80-b27b-11eb-8599-8abefcf7bd43.png">

Should I install something before?

**Comment by Funatiq** [comment]
Cub is included in CUDA 11 and newer. If you have to use an older CUDA version, you can download Cub from https://github.com/NVIDIA/cub.

**Comment by dancingpipi** [comment]
Thanks! My CUDA version is 10.0, I'll try to download cub
