### ISSUE TITLE
Why the SingleValueHashTable's  key does not support int32 or int64

### ISSUE THREAD

**Issue by wu-yy** [sleeepyjack/warpcore#2]

**Comment by wu-yy** [comment]
Why the SingleValueHashTable's  key does not support int32 or int64?

**Comment by sleeepyjack** [comment]
Most use cases use uint32/64 as their representation of key signatures. 

As a workaround, you can also use a regular type cast to convert your signed int keys to uint32 or uint64, respectively. 

Be aware that any converted type must be bitwise comparable, i.e. no padding bits.

In the future, we plan to allow dtypes that suffice the above mentioned constrains directly as key types so you won't need the additional type cast anymore.
