### ISSUE TITLE
UVM Question

### ISSUE THREAD

**Issue by pengwu22** [sleeepyjack/warpcore#3]
Hi developers! Is it built upon nvidia unified virtual memory? Thanks!

**Comment by sleeepyjack** [comment]
Hi @pw2393. Sorry for the late response. We do not use UVM in this approach as the random memory access pattern induced by the hash table's probing scheme doesn't play well with UVM's prefetching heuristics. Instead, in case the table does not fit into the VRAM of a single GPU, we propose a multi-GPU distribution scheme over a dense NVLink topology (see papers linked in the readme file). For the input/output vectors you are free to put them in UVM.
