### ISSUE TITLE
SingleValueHashTable key exists function ?

### ISSUE THREAD

**Issue by ecofriendlygeek** [sleeepyjack/warpcore#5]
Is it possible to check that a key exists with SingleValueHashTable ?
My testing shows that if a non-existent key is used to query, it returns a random value.

**Comment by Funatiq** [comment]
Yes, this is possible. The retrieve functions return a [status](https://github.com/sleeepyjack/warpcore/blob/master/include/warpcore/status.cuh) for each queried key which you can check for "key not found".

**Comment by ecofriendlygeek** [comment]
I am using this : std::cout << "Get errors: " << ((hash_table_t*)p_hash_table)->pop_status().get_errors() << std::endl;

Init errors: []
Value initialized to key 20 is 5
Insert errors: []
Value initialized to key 2 is 45
Insert errors: []
Get errors: []
Value retrieved for key 20 is 5
Get errors: []
Value retrieved for key 2 is 45
Get errors: []
Value retrieved for non-existent key 55 is 45

**Comment by Funatiq** [comment]
The status for non-existent keys is not an error (misbehaving hash table) but a warning (expected but maybe undesired). Use `get_warnings()` instead of `get_errors()` here, or just use the whole status you get from `pop_status()`.
I would also advise you to use the status from the retrieve functions instead of the status of the whole hash table. This way you will get a status for each key in the operation.

**Comment by ecofriendlygeek** [comment]
get_warnings on the hash table worked.

status from retrieve did not work
SingleValueHashTable : retrieve and retrieve_all are void functions, not sure how to get the status.
error: no suitable constructor exists to convert from "void" to "warpcore::Status"

**Comment by sleeepyjack** [comment]
You can attach a  [`status_handler`](https://github.com/sleeepyjack/warpcore/blob/ba5a6a84a8797464e2ce8dd03b269907ee70e7c2/include/warpcore/status.cuh#L296) to any bulk operation which writes out the return status for each input element. Just make sure to allocate and initialize an output vector of type `status_handler::base_type*` of the same length as the input vector and pass it to the function, e.g. [here](https://github.com/sleeepyjack/warpcore/blob/ba5a6a84a8797464e2ce8dd03b269907ee70e7c2/include/warpcore/single_value_hash_table.cuh#L247).

> SingleValueHashTable : retrieve and retrieve_all are void functions, not sure how to get the status.
> error: no suitable constructor exists to convert from "void" to "warpcore::Status"

Those functions do not return the status directly. Instead, they update the status field that is tied to the hash table object and can be queried using `hash_table.pop_status()` or `hash_table.peek_status()`.
